{
 "title": "Model Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "label": "Project Name", "query": { "query": "label_values(project)" } },
   { "name": "model", "label": "Model Name", "query": { "query": "label_values(model)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Metrics - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{metric_type=\"service_metrics\", project=\"$project\", model=\"$model\"}[1d]"
    }
   ]
  },
  {
   "title": "Performance Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{metric_type=\"performance\", project=\"$project\", model=\"$model\"}[1d]"
    }
   ]
  },
  {
   "title": "Data Integrity Violations",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{metric_type=\"data_integrity\", model=\"$model\", project=\"$project\"}[1d]"
    }
   ]
  },
  {
   "title": "Feature Drift Metrics",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{metric_type=\"drift\", project=\"$project\", model=\"$model\"}[1d]"
    }
   ]
  }
 ]
}